### ISSUE TITLE
multijournal ojs when activate plugin in principal site

### ISSUE THREAD

**Issue by cristiaan3003** [ajnyga/facebookFeed#2]
I have a multijournal ojs. When I activate plugin in principal cite I get: 

I use php 7 and ojs 3.1.1:

[Mon May 28 10:10:16.143900 2018] [:error] [pid 21909] [client 127.0.0.1:51114] PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /var/www/html/ojs-3.1.1/plugins/generic/facebookFeed/FacebookFeedBlockPlugin.inc.php:86\nStack trace:\n#0 /var/www/html/ojs-3.1.1/lib/pkp/classes/plugins/BlockPlugin.inc.php(178): FacebookFeedBlockPlugin->getContents(Object(TemplateManager), Object(Request))\n#1 /var/www/html/ojs-3.1.1/lib/pkp/classes/plugins/HookRegistry.inc.php(107): BlockPlugin->callback('Templates::Comm...', Array)\n#2 /var/www/html/ojs-3.1.1/lib/pkp/classes/template/PKPTemplateManager.inc.php(1145): HookRegistry::call('Templates::Comm...', Array)\n#3 /var/www/html/ojs-3.1.1/cache/t_compile/ade49584b259a94052943f98dbc0b6eb603691ca^%%40^408^4081C66E%%footer.tpl.php(9): PKPTemplateManager->smartyCallHook(Array, Object(TemplateManager))\n#4 /var/www/html/ojs-3.1.1/lib/pkp/lib/vendor/smarty/smarty/libs/Smarty.class.php(1870): include('/var/www/html/o...')\n#5 /var/www/html/ojs-3.1.1/lib/pkp/classes/template/PKPTemplateManager.inc.php(406): Smarty->_smarty_include(Array)\n#6 /var/www/html/oj in /var/www/html/ojs-3.1.1/plugins/generic/facebookFeed/FacebookFeedBlockPlugin.inc.php on line 86, referer: http://127.0.0.1/ojs-3.1.1/index.php/index

**Comment by ajnyga** [comment]
I have to check this. We do not use block plugins in the main site, so I have not tried to use it there. Probably not a big thing to fix.
